### ISSUE TITLE
Support development

### ISSUE THREAD

**Issue by Adam-Vandervorst** [fractarchy/fractagui#2]
Hi! 

I'd love to support your development of this project.
I've made similar out-of-the-box visualizations and can see the application to knowledge graphs.
Specifically, I'm working on a self-hosting editor written in MeTTa (Atomese 2.0, if you will), and it could be cool to incorporate this.

Please reach out to me at adam.vandervorst@singularitynet.io so we can discuss the possibilities.

**Comment by contrast-zone** [comment]
Hi,

What kind of collaboration exactly are you looking for? Maybe I could find some time to get to see FractaGUI actually being used somewhere. If you need some kind of different modularisation with FractaGUI, I can help you with that.

If you'd like to take this conversation to more personal level, you can find me here: ivan (dot) moony (at) gmail (dot) com, but I'm perfectly ok with discussing it here.
